### PR TITLE
Update version to 1.10.0

### PR DESCRIPTION
**Pull request by carterbox**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carterbox** [comment]
@conda-forge-admin, please rerender

**Comment by carterbox** [comment]
@conda-forge/help-ppc64le My PowerPC builds are mostly being killed during the test phase, but randomly pass. It doesn't seem to be a time-out because the jobs that are killed sometimes run shorter than the successful ones.


Here's an example of the log tail.

```
test/test_tomopy/test_recon/test_algorithm.py::ReconstructionAlgorithmTestCase::test_sirt_accel SKIPPED
test/test_tomopy/test_recon/test_algorithm.py::ReconstructionAlgorithmTestCase::test_sirt_gpu SKIPPED
test/test_tomopy/test_recon/test_algorithm.py::ReconstructionAlgorithmTestCase::test_tikh PASSED
test/test_tomopy/test_recon/test_algorithm.py::ReconstructionAlgorithmTestCase::test_tv PASSED
test/test_tomopy/test_recon/test_rotation.py::CenterFindingTestCase::test_find_center SKIPPED
test/test_tomopy/test_recon/test_rotation.py::CenterFindingTestCase::test_find_center_pc PASSED
test/test_tomopy/test_recon/test_rotation.py::CenterFindingTestCase::test_find_center_vo PASSED
/home/conda/feedstock_root/.scripts/build_steps.sh: line 67:   551 Killed                  conda $BUILD_CMD "${RECIPE_ROOT}" -m "${CI_SUPPORT}/${CONFIG}.yaml" --suppress-variables ${EXTRA_CB_OPTIONS:-} --clobber-file "${CI_SUPPORT}/clobber_${CONFIG}.yaml"
travis_time:end:02ffb809:start=1616693108853225562,finish=1616693638456361030,duration=529603135468,event=script
[0K[31;1mThe command "if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi" exited with 137.[0m
```

**Comment by mrakitin** [comment]
Hi @carterbox, do you know why the artifacts from this unmerged PR have leaked into anaconda.org already?
image

The recipe in `master` currently shows version 1.9.1 build 3.

**Comment by carterbox** [comment]
Yes, I accidentally pushed this branch to the upstream when I was opening this PR. I thought those builds would cancel when I updated the branch. If they are broken, then open an Issue. Otherwise, there shouldn't be a problem because only the powerpc builds are failing here.

**Comment by carterbox** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
