### PR TITLE
Add CUDA builds

### PR DESCRIPTION
**Pull request by carterbox**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carterbox** [comment]
```
/azure-pipelines.yml: Could not find /.azure-pipelines/azure-pipelines-linux.yml
in repository self hosted on https://api.github.com using commit
d9ef6087b60011dde81b231af59d15e57b157262. GitHub reported the error, "Not Found"
```

**Comment by carterbox** [comment]
This cuda installer is really annoying because it finds everything using absolute paths. It wants to find perl at `/usr/bin/perl`, but I can't install anything there, so it the install fails.

**Comment by carterbox** [comment]
For Posterity:

TomoPy does not offer a conda-forge CUDA build because conda-forge does not offer a build environment with NVCC installed. I was trying to install NVCC myself into the Linux build environment in this pull, but I was facing many install errors that I could not resolve.

**Comment by leofang** [comment]
@carterbox can you try adding a file `yum_requirements.txt` to avoid the `perl` error? See https://github.com/conda-forge/cudatoolkit-dev-feedstock/blob/master/recipe/yum_requirements.txt.
I understand the frustration of building non-Python packages. I hope the current efforts happening elsewhere (such as the link above) can make it easier to build CUDA-dependent packages in Conda.

**Pull request closed without merging**
