### PR TITLE
Second CUDA build attempt

### PR DESCRIPTION
**Pull request by carterbox**
I'm trying a CUDA build again. I can't re-open the old pull. #18 

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carterbox** [comment]
Is it possible to install only the cudatoolkit components needed by using a yum install of the toolkit from the official NVIDIA repo? This would probably always grab the most recent version of the cudatoolkit whenever the feedstock was built.

**Comment by carterbox** [comment]
Thanks, @leofang! I got it built. I just need do some testing to see if it will actually run. Ideally we should have automated tests for the CUDA enabled function. (Related to tomopy/tomopy#422).

**Comment by carterbox** [comment]
@conda-forge/help-python-c Does this conform to the current (tentative?) conventions of publishing a CUDA enabled package?

- [x] Uses the `main::cudatoolkit` package as a dependency to track the toolkit used at compile time
- [x] Includes `cudaX.X` in the build string to indicate the major and minor CUDA version used at compile time
- [x] Bumps the non-CUDA build numbers to 100, so they are preferred over CUDA builds

**Comment by carterbox** [comment]
I'm holding this until the next release, so that people aren't updating from from build 0 to build 101 for no reason.

**Comment by leofang** [comment]
@carterbox Thanks a lot for the effort! For your earlier note:
>  Ideally we should have automated tests for the CUDA enabled function. 

Did you find a way to test GPU functions in this PR?

**Comment by carterbox** [comment]
@leofang Yes. I used Docker and the `run_locally.py` script to test these builds on my computer before publishing the releases.

**Comment by leofang** [comment]
@carterbox OK I see. My understanding is that conda-forge's CI doesn't have GPU resource for testing, am I right?

**Comment by carterbox** [comment]
@leofang That's right.

**Pull request merged**
