### PR TITLE
BLD: Use conda-forge nvcc

### PR DESCRIPTION
**Pull request by carterbox**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carterbox** [comment]
@jakirkham, This is the PR I'm working on. I thought my questions would be useful for that Issue (conda-forge/conda-forge.github.io#901) because I expect anything that I have questions about would be useful to address in the documentation.

**Comment by jakirkham** [comment]
No worries. I understand. That may still be true. Though as we were turning increasingly to debugging your specific problem, it made more sense to segue to your PR. Hope that is ok. 🙂

Did you try setting `CUDA_INCLUDE_DIRS` in your build explicitly?

**Comment by carterbox** [comment]
Yes. CMake is still having trouble finding CUDA. It would help if I could play with this build environment locally.

**Comment by jakirkham** [comment]
Sure. Would install Docker on your machine. Then create a Python environment locally that has `shyaml` in it. With these in place, run `python build-locally.py` in the top-level directory of the feedstock. This should provide you the option to build one of these environments. You can then inspect the running Docker container or do a post-mortem inspection of it.

**Comment by carterbox** [comment]
I restarted a (failed) container and explored the filesystem using `docker exec -t -i container_name /bin/bash`. I could not find any kind of CUDA files in the filesystem outside of the conda-build environment. This environment dumped into the `build_artifacts` folder. I also didn't find any `$CUDA_HOME` environment variable set inside the container. I was expecting this because it is used in the activate script of the NVCC package.

There are no headers included with the `cudatoolkit` package. Should I make a `cudatoolkit-include` package? It could probably be build from the same recipe as `nvcc_linux-64`.

**Comment by carterbox** [comment]
I think I was using the wrong image to build locally. I forgot to install `shyaml`, and perhaps this package is required for the `conda-forge/linux-anvil-cuda` image to be downloaded.

**Comment by carterbox** [comment]
@jakirkham, Thanks for you help, but I think the problem is with TomoPy's messy build system. I'll need to work on this elsewhere.

**Comment by carterbox** [comment]
@jakirkham CMake will have trouble verifying that the CUDA compiler is functioning because it uses the location of the NVCC binary to find the other CUDA libraries and headers. Linking the CUDA includes directory to the Conda prefix solves the problem. `ln -s ${CUDA_HOME}/include/* ${CONDA_PREFIX}/include/`. Maybe the `nvcc_linux-64` package should do this autmatically?

**Comment by jakirkham** [comment]
Thanks for investigating and sharing this feedback. Could you please [raise an issue on the `nvcc` feedstock]( https://github.com/conda-forge/nvcc-feedstock/issues ) with your findings?

**Comment by carterbox** [comment]
Done. It's conda-forge/nvcc-feedstock#29.

**Pull request merged**
